name: PR check finished

on:
  check_run:
    types: [completed]


jobs:
  echo:
    runs-on: ubuntu-latest
    if:
    steps:
      - name: Echo
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}