name: PR creation workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master


jobs:
  echo:
    runs-on: ubuntu-latest
    # from branch autodeploy/* to branch master
    if: ${{ github.head_ref == 'autodeploy/*' && github.base_ref == 'master' }}
    steps:
      - name: Echo
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}