name: TIMER

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - master
      - main
#  push:
#    branches:
#      - "*"

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: wait 0.5 minutes
        run: sleep 30