name: TIMER

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - *

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: wait 1 minutes
        run: sleep 60